dataloader:
  batch_size: 128
  sample_size: 256
  shuffle: true
  test_dataset:
    coefficient: 0.01
    params:
      data_root: ./ARMD/Data/diffusion_training_data/TSLA/TSLA_training_data.csv
      distribution: geometric
      name: TSLA
      neg_one_to_one: true
      period: test
      proportion: 0.2
      save2npy: true
      seed: 2024
      style: separate
      window: 192
    sampling_steps: 200
    step_size: 0.05
    target: Utils.Data_utils.real_datasets.CustomDataset
  train_dataset:
    params:
      data_root: ./ARMD/Data/diffusion_training_data/TSLA/TSLA_training_data.csv
      name: TSLA
      neg_one_to_one: true
      period: train
      proportion: 0.8
      save2npy: true
      seed: 2024
      window: 192
    target: Utils.Data_utils.real_datasets.CustomDataset
model:
  params:
    beta_schedule: cosine
    feature_size: 10
    loss_type: l2
    regime_conditional: true
    sampling_timesteps: 1
    seq_length: 96
    timesteps: 96
    w_grad: true
  target: Models.autoregressive_diffusion.armd.ARMD
solver:
  base_lr: 0.001
  ema:
    decay: 0.995
    update_interval: 10
  gradient_accumulate_every: 2
  max_epochs: 2000
  results_folder: ./Checkpoints_TSLA
  save_cycle: 1800
  scheduler:
    params:
      factor: 0.5
      min_lr: 1.0e-05
      patience: 4000
      threshold: 0.1
      threshold_mode: rel
      verbose: false
      warmup: 500
      warmup_lr: 0.0008
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
